"""table init

Revision ID: 6762f100411d
Revises: 7d78b14f7e9c
Create Date: 2019-07-24 10:37:27.828765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6762f100411d'
down_revision = '7d78b14f7e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('remote_addr', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'remote_addr')
    # ### end Alembic commands ###
